## Linear Algebra In Python

In [5]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
A_T = A.T  # or np.transpose(A)

print("Original matrix A:\n", A)


Original matrix A:
 [[1 2]
 [3 4]]


In [6]:
A_T = A.T  # or np.transpose(A)
print("Transpose A^T:\n", A_T)

Transpose A^T:
 [[1 3]
 [2 4]]


In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_matrix = np.dot(A, B)   # or A @ B
print("Matrix product A · B:\n", dot_matrix)

Matrix product A · B:
 [[19 22]
 [43 50]]


In [3]:
A = np.array([[1, 2], [3, 4]])

det = np.linalg.det(A)
print("Determinant of A:", det)

Determinant of A: -2.0000000000000004


In [4]:
# Compute the inverse
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

Matrix A:
 [[1 2]
 [3 4]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## 2D Pose in Python